### ISSUE TITLE
true/false won't be parsed to boolean

### ISSUE THREAD

**Issue by StarpTech** [mcollina/tinysonic#1]
Is this the correct behavior? I think its safe to parse `"true"` as `true`. I would create a PR.

e.g
`"topic:test,pubsub$:true"` => `{ topic: "test", pubsub$: true }`
`"topic:test,pubsub$:false"` => `{ topic: "test", pubsub$: false }`

**Comment by mcollina** [comment]
definitely. Go ahead :).
