### ISSUE TITLE
Feature Request: Stringify Method similar to JSON.stringify

### ISSUE THREAD

**Issue by quinton-ashley** [mcollina/tinysonic#4]

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by quinton-ashley** [comment]
Yeah I could try it.  jsonic will need to become a class with methods instead of just a single function though.

**Comment by mcollina** [comment]
It would not need to become a class, stringify it’s just another function. We can have .parse and .stringify, similar to JSON.

I have no time to implement this feature. I’m happy to review a PR.

**Comment by JairusSW** [comment]
@mcollina @quinton-ashley I'm interested in making a stringify function. For now, I'm going to try to make (optimize) the parse function to be faster than JSON. I made a very fast stringify function that beats out JSON by a large margin in kati (https://www.npmjs.com/package/kati). Hopefully, I can adapt it to TinySonic and make it a fully-fledged package. :)

**Comment by mcollina** [comment]
Go for it! I'm not maintaining this module much anyway!

**Comment by quinton-ashley** [comment]
@JairusSW yeah that'd be great!

**Comment by JairusSW** [comment]
@mcollina @quinton-ashley , I finished it. Let me just clean up the project and I'll submit a pull request. 😄 
Btw, check out the benches!
```
TinySonic Stringify x 7,089,854 ops/sec ±9.23% (82 runs sampled) 🔥
Jsonic Stringify x 1,565,541 ops/sec ±1.01% (88 runs sampled)
JSON Stringify x 2,562,274 ops/sec ±0.91% (87 runs sampled)
TinySonic Parse x 2,067,367 ops/sec ±2.39% (88 runs sampled)
Jsonic Parse x 159,366 ops/sec ±9.79% (91 runs sampled)
JSON Parse x 1,434,668 ops/sec ±13.47% (81 runs sampled)
```

**Comment by JairusSW** [comment]
Sent a pull request! 😉

**Comment by JairusSW** [comment]
@mcollina, close?

**Comment by mcollina** [comment]
Thanks!
